# name: Hello World

# on: push

# jobs:
#   hello:
#     runs-on: ubuntu-latest

#     steps:
#       - run: echo "Hello from GitHub Actions"


name: Question 1

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Dynamic Info
        run: |
          echo "Hello ${{ github.actor }}"
          echo "You pushed to ${{ github.ref_name }}"
          echo "from repository ${{ github.event.repository.name }}"
          echo "at $(TZ=Asia/Kolkata date '+%Y-%m-%d %H:%M IST')"